sudo: required

services:
  - docker

before_install:
  - docker build -t chancypolyhedra .
  - docker run -d chancypolyhedra
  - docker ps -a

script:
  - docker exec $(docker ps -lq) /bin/sh -c "/app/bin/chancypolyhedra_tests"
